# Generated by Django 3.2.17 on 2023-02-08 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Is_active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Is_staff',
            new_name='is_staff',
        ),
    ]
